# Generated by Django 5.1.3 on 2025-01-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_Notification',
        ),
    ]
