# Generated by Django 5.1.3 on 2025-01-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0003_remove_job_date_job_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_posted',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='', upload_to='company_logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='passoutyear',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(max_length=500),
        ),
    ]
