# Generated by Django 5.1.3 on 2025-01-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0004_rename_date_posted_job_date_alter_job_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.AddField(
            model_name='notification',
            name='tutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placementapps.tbl_tutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
