# Generated by Django 5.1.3 on 2025-01-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0006_notification_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placementapps.job'),
            preserve_default=False,
        ),
    ]
