# Generated by Django 5.1.3 on 2025-01-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0008_studentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placementapps.job')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placementapps.tbl_tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
