# Generated by Django 5.1.3 on 2025-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0010_rename_seen_studentnotification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tutor',
            name='batch',
            field=models.CharField(max_length=15),
        ),
    ]
