# Generated by Django 5.1.3 on 2025-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0011_alter_tbl_tutor_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tutor',
            name='batch',
            field=models.CharField(max_length=20),
        ),
    ]
