# Generated by Django 6.0.4 on 2026-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0013_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
