# Generated by Django 5.2 on 2026-09-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0014_alter_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResumeScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('semantic_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('missing_skills', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_screening', to='placementapps.jobapplication')),
            ],
        ),
    ]
