# Generated by Django 5.2 on 2026-09-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0015_airesumescreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='admin_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Admin Approved'), ('Rejected', 'Admin Rejected')], default='Pending', max_length=10),
        ),
    ]
