# Generated by Django 5.2 on 2026-09-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0016_jobapplication_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='admin_status',
            field=models.CharField(choices=[('Admin_Pending', 'Pending'), ('Admin_Approved', 'Admin Approved'), ('Admin_Rejected', 'Admin Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
