# Generated by Django 5.2 on 2026-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapps', '0017_alter_jobapplication_admin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='admin_status',
            field=models.CharField(choices=[('Admin_Pending', 'Admin_Pending'), ('Admin_Approved', 'Admin Approved'), ('Admin_Rejected', 'Admin Rejected')], default='Admin_Pending', max_length=50),
        ),
    ]
