from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('courseslisting/<int:department_id>/', views.courses_listing, name='courses_listing'),
    path("", views.index,name='index'),
    path('user_index/', views.user_index, name='user_index'),
    path('tutor_register/', views.register_tutor, name='tutor_register'),
    path('tutor_index/', views.tutor_index, name='tutor_index'),
    path('login/', views.login, name='login'), 
    path('logout/', views.logout, name='logout'), 
    path('admin_index/',views.admin_index,name="admin_index"), 
    path('admin_view_tutor/',views.admin_view_tutor,name='admin_view_tutor'),
    path('admin_approved_tutor/',views.admin_approved_tutor,name='admin_approved_tutor'),
    path('admin_rejected_tutor/',views.admin_rejected_tutor,name='admin_rejected_tutor'),
    path('admin_view_approved_tutor/',views.admin_view_approved_tutor,name='admin_view_approved_tutor'),
    path('admin_view_rejected_tutor/',views.admin_view_rejected_tutor,name='admin_view_rejected_tutor'),
    path('list_student/', views.list_student, name='list_student'),
    path('delete_student/', views.delete_student, name='delete_student'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('edit_profile/<int:student_id>/', views.edit_profile, name='edit_profile'),
    path('tutor_profile/', views.tutor_profile, name='tutor_profile'),
    path('tutor_editprofile/', views.tutor_editprofile, name='tutor_editprofile'),
    path('add_department/', views.add_department, name='add_department'),
    path('list_department/', views.list_department, name='list_department'),
    path('edit_department/<int:department_id>/', views.edit_department, name='edit_department'),
    path('delete_department/', views.delete_department, name='delete_department'),
    path('view_department/', views.view_department, name='view_department'),
    path('job_list/', views.job_list, name='job_list'),
    path('job_detail/', views.job_detail, name='job_detail'),
    path('admin_addjoblist/', views.admin_addjoblist, name='admin_addjoblist'),
    path('admin_joblist/', views.admin_joblist, name='admin_joblist'),
    path('admin_jobdetail/', views.admin_jobdetail, name='admin_jobdetail'),
    path('user_job_list/', views.user_job_list, name='user_job_list'),
    path('search-jobs/', views.search_jobs, name='search_jobs'),
    path('user_job_detail/<int:job_id>/', views.user_job_detail, name='user_job_detail'),
    path('tutor_job_list/', views.tutor_job_list, name='tutor_job_list'),
    path('tutor_job_detail/<int:id>/', views.tutor_job_detail, name='tutor_job_detail'),
    path('job_application/<int:job_id>/', views.apply_for_job, name='apply_for_job'), 
    path('download_resume/<int:student_id>/', views.download_resume, name='download_resume'),
    path('admin_training_sessions/', views.admin_training_sessions, name='admin_training_sessions'),
    path('admin_sessionlist/', views.admin_sessionlist, name='admin_sessionlist'),
    path('delete_TrainingSession/<int:session_id>/', views.delete_TrainingSession, name='delete_TrainingSession'),
    path('admin_editsession/<int:session_id>/', views.admin_editsession, name='admin_editsession'),
    path('admin_applylist/<int:job_id>/', views.admin_applylist, name='admin_applylist'),
    path('tutor_applylist/', views.tutor_applylist, name='tutor_applylist'),
    path('user_about/', views.user_about, name='user_about'),
    path('tutor_about/', views.tutor_about, name='tutor_about'),
    path('contact/', views.contact_view, name='contact'), 
    path('add_course/<int:department_id>/', views.add_course, name='add_course'),
    path('delete_course/<int:id>/', views.delete_course, name='delete_course'),
    path('tutor_sessionlist/', views.tutor_sessionlist, name='tutor_sessionlist'), 
    path('user_sessionlist/', views.user_sessionlist, name='user_sessionlist'), 
    path('admin_applysessionlist/<int:session_id>/', views.admin_applysessionlist, name='admin_applysessionlist'),
    path('download_excel/', views.download_excel, name='download_excel'),
    path('admin_studentslist/', views.admin_studentslist, name='admin_studentslist'),
    path('apply_for_session/', views.apply_for_session, name='apply_for_session'),
    path('tutor_jobapplylist/<int:job_id>/', views.tutor_jobapplylist, name='tutor_jobapplylist'),
    path('session_applylist/<int:session_id>/', views.session_applylist, name='session_applylist'),
    path('applied-sessions/', views.user_applied_sessions, name='user_applied_sessions'),
    path('jobdownload_excel/<int:job_id>/', views.download_applications_excel, name='jobdownload_excel'),
    path('user_applied_job/', views.user_applied_jobs, name='user_applied_jobs'),
    path('register/', views.register_tutor, name='register_tutor'),
    path('upload_excel/', views.upload_excel, name='upload_excel'), 
    path('view_final_year_student/', views.view_final_year_student, name='view_final_year_student'),
    path('approve_application/<int:application_id>/', views.approve_application, name='approve_application'),
    path('reject_application/<int:application_id>/', views.reject_application, name='reject_application'),
    path('tutor/notifications/', views.tutor_notifications, name='tutor_notifications'),
    path('reapprove_application/<int:application_id>/',views.reapprove_application, name='reapprove_application'),
    path('tutor/notifications/read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'), 
    path('approve/<int:application_id>/', views.approve_application, name='approve_application'),
    path('reject/<int:application_id>/', views.reject_application, name='reject_application'),
    path('notifications/', views.student_notifications, name='student_notifications'),
   path('delete_job/<int:job_id>/', views.delete_job, name='delete_job'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
